lib/genpptx.js

Add presProps.xml, viewProps.xml, theme/theme1.xml, and tableStyles.xml relationships to ppt/_rels/presentation.xml.rels after all slides are added. Required for use with latest version of Apple Keynote; Microsoft PowerPoint functions properly with or without.

PPTX fix for latest version of Apple Keynote

---

lib/genxlsx.js

It's now possible to set the cols width for a sheet just by setting an ordered array as a sheetObj property named "width". 
For example: "sheet1.width = [20,50,30]" will set the first column of sheet1 to 20, the second to 50 and the third to 30.

Set cols width in xlsx

---

lib/msofficegen.js

Now if you add a GIF image, you will get a broken `.docx` file.
It will show the following message:
And this PR:
- Add `<Default ContentType="image/gif" Extension="gif"/>` in `[Content_Types].xml`.

add support for GIF

---

lib/msexcel-builder.js

Removing special characters and consecutive spaces in Sheet `name` will prevent document from being corrupt.

Prevent corrupt Excel sheet

---

lib/genpptx.js

Uses pptWidth for obj cx and x calculations instead of hard coded number. This picks up the value set for pptWidth when setWidescreen(true).

PPTX Widescreen Centering Fix

---

lib/docxtable.js

The cellColWidth option that is copied to the w:w on a w:tcW only works if the w:gridCol is a non-zero value. With w:gridCol set to "1", it is now possible to set table columns to different widths by using the cellColWidth on the columns for the first (generally the header) row, rather than having to set a constant column width in the table options.

Provide varying column sizes in Word tables

---

examples/make_docx.js

The example was passing officegen() a string, 'docx', so it wasn't obvious where to put document-level options. Used the "type" key in a map instead along with an explicit orientation.

Use explicit options in docx example

---

lib/docxtable.js

I've added the inside table borders when the "borders" option is set for a table. In my opinion this is typically what someone is looking for when they turn borders on - the "grid" effect of having every cell inside a border. 
If it would be better to have separate options for the different positions of borders, I'm happy to do that instead.

All inside table borders

---

examples/make_pptx_charts.js
lib/officechart.js
package.json
test_files/charts-data.js

Fairly new to this library - but my testing seems to indicate a missing if statement for setting line  chart data in `lib/officechart.js`.

Fix line chart support

---

README.md
examples/make_pptx_charts.js
lib/charts.js
test_files/charts-data.js

Based on the column chart - this PR adds a simple way to generate stacked columns:

Add support for stacked column charts

---

lib/basicgen.js

There seems to be a race condition where the sample[n].xlsx files are 
removed before the archiver has a chance to append/include them.
This causes the error 'no such file or directory sample[n].xlsx'.
This PR moves the removal of temporary resources to much later in the 
build process - after all the resources have been added.

Remove temporary resources just before closing

---

lib/docxtable.js

In example "make_table_cell_span.js" on line 58 opts: {gridSpan: 2} not work without this changes

Add support to grid span option

---

lib/genofficetable.js

Added cell level properties for making the cell bold or italic by giving the following properties
- bold: it receives the parameters as an array of array(e.g [["0","1","0","1"],["0","0","0","1"],["0","1","0","0"]])the values for the  array can be "1" for bold and "0" normal ,default is set to normal
- italics: it receives the parameters as an array of array(e.g [["0","1","0","1"],["0","0","0","1"],["0","1","0","0"]])the values for the  array can be "1" for italics and "0" normal ,default is set to normal 
Example:
slide.addTable(rows, {'tabstyle':'{F5AB1C69-6EDB-4FF4-983F-18BD219EF322}',
'bold':[["0","1","1"],["0","1","1"],["0","1","1"],["0","1","1"]],
'italics':[["0","1","1"],["1","1","0"],["1","1","1"],["1","1","1"]]});

Table properties

---

README.md
examples/make_pptx.js
lib/genofficetable.js

Added ability to set cell attributes of font family, font size, font color (new), bold, italics, alignment, and fill color (new), overriding any table level options or defaults.  Attempted to keep naming/code patterns consistent with those used for docx tables (in docxtable.js).

Enable cell specific formatting in PowerPoint tables

---

CHANGELOG
lib/gendocx.js
package.json

Fix issue with createByJson for docx documents which would strip the very first element from the JSON object which is outlined in https://github.com/Ziv-Barber/officegen/issues/208.
`shift()` removes the first element from the array, so it's used to make the new paragraph but then is never rendered.

Fix issue with createByJson

---

README.md

Came across this function and it was pretty useful for what I was building, so I think it would be helpful if it was in the public API

Add pptx.setSlideSize option to docs

---

lib/docx-p.js
lib/gendocx.js

This bug was introduced by 74e04fafe664f07c4012b77f4002a64e3e276e2a when the paragraph code was moved into it's own file. This accounts for the unused require('path') in gendocx.js
Bug: https://github.com/Ziv-Barber/officegen/issues/191

Fix missing require('path')

---

lib/gendocx.js

Word does not support decimal values, this solves the issue allowing for better control over the size of an image.

Round cx and cy values for images

---

lib/msexcel-builder.js

I get this warning when building in my TypeScript + Electron project.
```
WARNING in ./node_modules/officegen/lib/msexcel-builder.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find SourceMap 'msexcel-builder.js.map': Error: Can't resolve './msexcel-builder.js.map' in '<project_dir>/node_modules/officegen/lib'
```
No other files reference source maps, so I assume it's ok to remove this.

Remove missing sourcemap url

---

lib/docx/gendocx.js

This was partially fixed by commit 4032364c081ea2b3cb76c03fca311c480cd369e3, but only in the `wp:extent` tag. The docx I generated still had decimals in the `a:ext` tag, and Word was complaining that the file was corrupt.
With this fix, the docx file was properly generated.

Round cx and cy values for images in a:ext tag
