- lib/gendocx.js
This path allow use "link" option for addImage function for creating hyperlink in docx file:
Usage:
````
var p = docx.createP();
p.addImage(..., { "link": "http://www.google.com" });
````
Based on https://github.com/Ziv-Barber/officegen/pull/39
> Docx hyper link support for addImage

- README.md
- examples/make_docx.js
- examples/make_docx_json.js
- lib/docxtable.js
- lib/gendocx.js
```
var pObj = docx.createP ();
pObj.addHorizontalLine ();
```
looks like:
----
```
var pObj = docx.createP ({ backline: 'E0E0E0' });
pObj.addText ( 'Backline text1' );
pObj.addText ( ' text2' );
```
looks like:
> docx: add horizontal line and back line

- README.md
- examples/make_pptx.js
- lib/genofficetable.js
In these commits, we are adding options that customize the tables for pptx generation.
They are pretty simple (cf README and/or example).
> Add options for pptx table : font and layout

- README.md
- lib/basicgen.js
This patch can help a little bit some people for debugging.
> Add debug messages in basicgen.js and add 'verbose' option in README

- lib/genpptx.js
Simple patch.
Everything is said in title.
I've read that you're current doing a rework of charts, but as I needed this patch, I've done it and publishing it. It could be usefull for others while waiting for your rework.
~~Important: this precise commit has NOT been tested properly, because I'm having error on master with charts (probably same issue than Issue #103 ).
In fact, this commit is a cherry-pick from our fork (branch https://github.com/ezeeworld/officegen/tree/workingForUs). And the patch is tested and working properly in our branch.~~
> For pptx addChart(), add support for positionning options (x,y,cx,cy)

- examples/make_table_cell_span.js
> make table on .docx grid-span enabled

- README.md
- lib/gendocx.js
- package.json
Per tickets:
https://github.com/Ziv-Barber/officegen/issues/143
https://github.com/Ziv-Barber/officegen/issues/36
Minor change per spec:
https://msdn.microsoft.com/en-us/library/ee922775(office.14).aspx#odc_Office14_ta_WorkingWithNumbering_MarkupSimpleBulleted
> Added support for bullets (they weren't working, and were just showing numbers)

- README.md
- examples/make_docx.js
- lib/gendocx.js
```javascript
var pObj = docx.createP ();
pObj.addText ( 'Regular text with ' );
pObj.addText ( 'hyperlink', { link: 'https://github.com' } );
```
> Ability to make text hyperlinks in docx

- lib/gendocx.js
It sets chinese font is invalid by word.
> fixed font_face display exception on chinse font.

- lib/genofficetable.js
- lib/genpptx.js
In the project I work on I needed to slightly change the default table styling used in generated PowerPoint file. So made this through adding new 'tableStyleId' option, and suppose, that this small change can be useful for others too.
> Added support of tableStyleId option.

- lib/genofficetable.js
Table Properties :
-  alignment can be set by passing align:['l','l','r','ctr'] array where each value of array corresponds to column in table default is ctr.
- tablestyle can be set by passing tabstyle:'{F5AB1C69-6EDB-4FF4-983F-18BD219EF322}' in options
> alignmnet and table style

- lib/docxtable.js
- lib/gendocx.js
- test/test-docx.js
Compared to the output of google docs and with help from this [article](http://openxmldeveloper.org/blog/b/openxmldeveloper/archive/2007/04/09/rtl-text.aspx)
> Add RTL support

- lib/docxtable.js
With this patch, Width on cells docx table now works.
> Working Cell Width

- examples/make_docx.js
- lib/gendocx.js
- manual/README-docx.md
This adds the option to create strikethrough text in docx documents.
> Add strikethrough option for docx

- lib/basicgen.js
> Replace recursion with iteration

- README.md
- lib/docxtable.js
- package.json
- tests/docx.test.js
More than happy to make changes since this is my first pull request on Github.
> Allow line breaks in Word table cells

- lib/docx/docxtable.js
- lib/docx/gendocx.js
- manual/README-docx.md
Add 'indentFirstLine' attribute for paragraph,  'indent' attribute  for  table
> Add 'indentFirstLine' attribute for paragraph,  'indent' attribute  for  table

- examples/make_docx.js
- lib/docx/gendocx.js
- manual/docx/README.md
Created this pull request for feature request [Feature request: ability to specify list level/depth for Docx](https://github.com/Ziv-Barber/officegen/issues/321)
> Feature request: ability to specify list level/depth for Docx

- lib/docx/docxtable.js
1. Possibility to create page-wide tables with tableWidth table option
2. Possibility to merge table cells vertically with `vMerge` cell option
> More options for tables

- README.md
```suggestion
add JavaScript syntax
```
> add syntax
